swagger: '2.0'
info:
  description: >-
    This is a server controlling flipdots.  You can find out more about
    Nerdmanufaktur at
    [http://nerdmanufaktur.berlin](http://nerdmanufaktur.berlin). For this
    sample, you can use the api key `foobar` to test the authorization filters.
  version: 1.0.0
  title: Nerdmanufaktur Flipdot API
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: hi@nerdmanufakur.berlin
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: api.nerdmanufaktur.berlin
basePath: /v1
tags:
  - name: flipdot
    description: FaaS - Flipdot as a service
    externalDocs:
      description: Find out more
      url: 'https://nerdmanufaktur.berlin'
  - name: user
    description: Operations about flipdot
    externalDocs:
      description: Find out more
      url: 'https://nerdmanufaktur.berlin'
  - name: applicationInstance
    description: Operations about application instances
    externalDocs:
      description: Find out more
      url: 'https://nerdmanufaktur.berlin'
  - name: application
    description: Operations about applications
    externalDocs:
      description: Find out more
      url: 'https://nerdmanufaktur.berlin'
schemes:
  - http
paths:
  /flipdot:
    post:
      tags:
        - flipdot
      summary: Create flipdot
      description: This can only be done by the logged in admin.
      operationId: createFlipdot
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Created flipdot object
          required: true
          schema:
            $ref: '#/definitions/Flipdot'
      responses:
        default:
          description: successful operation
  '/flipdot/{flipdotid}/start':
    post:
      tags:
        - flipdot
      summary: Start flipdot
      description: ''
      operationId: startFlipdot
      produces:
        - application/xml
        - application/json
      parameters:
        - name: flipdotid
          in: path
          description: Start flipdot. User needs to own flipdot.
          required: true
          type: string
      responses:
        default:
          description: successful operation
  '/flipdot/{flipdotid}/stop':
    post:
      tags:
        - flipdot
      summary: Stop flipdot
      description: ''
      operationId: stopFlipdot
      produces:
        - application/xml
        - application/json
      parameters:
        - name: flipdotid
          in: path
          description: Stop flipdot. User needs to own flipdot.
          required: true
          type: string
      responses:
        default:
          description: successful operation
  '/flipdot/{flipdotid}':
    get:
      tags:
        - flipdot
      summary: Get Flipdot by flipdot id
      description: ''
      operationId: getFlipdotByName
      produces:
        - application/xml
        - application/json
      parameters:
        - name: flipdotid
          in: path
          description: 'The name that needs to be fetched. Use flipdot1 for testing. '
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Flipdot'
        '400':
          description: Invalid flipdot id supplied
        '404':
          description: Flipdot not found
    put:
      tags:
        - flipdot
      summary: Updated flipdot
      description: This can only be done by the logged in user for flipdots he owns except for admins.
      operationId: updateFlipdot
      produces:
        - application/xml
        - application/json
      parameters:
        - name: flipdotid
          in: path
          description: name that need to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated flipdot object
          required: true
          schema:
            $ref: '#/definitions/Flipdot'
      responses:
        '400':
          description: Invalid Flipdot supplied
        '404':
          description: Flipdot not found
    delete:
      tags:
        - flipdot
      summary: Delete flipdot
      description: This can only be done by the logged in user.
      operationId: deleteFlipdot
      produces:
        - application/xml
        - application/json
      parameters:
        - name: flipdotid
          in: path
          description: The name that needs to be deleted
          required: true
          type: string
      responses:
        '400':
          description: Invalid flipdot id supplied
        '404':
          description: Flipdot not found
  /user:
    get:
      tags:
        - user
      summary: Get currently logged in user
      description: This can only be done by the logged in user.
      operationId: getLoggedInUser
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    post:
      tags:
        - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Created user object. Only admins can do this.
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        default:
          description: successful operation
  '/user/{userid}':
    get:
      tags:
        - user
      summary: Get user by user name
      description: Except for admins only the logged in user can be fetched.
      operationId: getUserByName
      produces:
        - application/xml
        - application/json
      parameters:
        - name: userid
          in: path
          description: The user id that needs to be fetched.
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
    put:
      tags:
        - user
      summary: Updated user
      description: This can only be done by the logged in user for himself except for admins.
      operationId: updateUser
      produces:
        - application/xml
        - application/json
      parameters:
        - name: userid
          in: path
          description: The user id that need to be updated.
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '400':
          description: Invalid user supplied
        '404':
          description: User not found
    delete:
      tags:
        - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      produces:
        - application/xml
        - application/json
      parameters:
        - name: userid
          in: path
          description: The user id that needs to be deleted. A cascading deletion process is triggered. All corresponding flipdots and application instances are deleted as well. Developer accounts can't be deleted via the API.
          required: true
          type: string
      responses:
        '400':
          description: Invalid username supplied
        '404':
          description: User not found
  '/applicationInstance/{applicationinstanceuuid}':
    get:
      tags:
        - applicationInstance
      summary: Get application instance by uuid
      description: ''
      operationId: getApplicationInstanceByUUID
      produces:
        - application/xml
        - application/json
      parameters:
        - name: applicationinstanceuuid
          in: path
          description: The id that needs to be fetched.
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApplicationInstance'
        '400':
          description: Invalid application instance id supplied
        '404':
          description: Application instance not found
    post:
      tags:
        - applicationInstance
      summary: Trigger a webhook
      description: ''
      operationId: triggerWebhook
      produces:
        - application/xml
        - application/json
      parameters:
        - name: applicationinstanceuuid
          in: path
          description: Trigger an application instances webhook. It can have multiple ones. The post data is sent to the app unchanged. Also there's no authentication required for this call.
          required: true
          type: string
      responses:
        default:
          description: successful operation
  '/application/{applicationname}':
    get:
      tags:
        - application
      summary: Get application by name
      description: ''
      operationId: getApplicationByName
      produces:
        - application/xml
        - application/json
      parameters:
        - name: applicationname
          in: path
          description: The name that needs to be fetched.
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Application'
        '400':
          description: Invalid application id supplied
        '404':
          description: Application not found
  '/application/{applicationname}/applicationSetting':
    get:
      tags:
        - application
      summary: Get application setting by application id
      description: ''
      operationId: getApplicationSettingByName
      produces:
        - application/xml
        - application/json
      parameters:
        - name: applicationname
          in: path
          description: The name of settings application that needs to be fetched.
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApplicationSetting'
        '400':
          description: Invalid application id supplied
        '404':
          description: Application not found
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://api.nerdmanufaktur.berlin/oauth/dialog'
    flow: implicit
    scopes:
      'write:user': modify users
      'read:user': read users
      'write:flipdot': modify flipdots
      'read:flipdot': read flipdot
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      password:
        type: string
      lastLogin:
        type: string
        format: date-time
      isDeveloper:
        type: boolean
        default: false
      applications:
        type: array
        items:
          $ref: '#/definitions/User'
    xml:
      name: User
  Application:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      description:
        type: string
      version:
        type: integer
      developer:
        $ref: '#/definitions/User'
    xml:
      name: Application
  ApplicationInstance:
    type: object
    properties:
      id:
        type: integer
        format: int64
      application:
        $ref: '#/definitions/Application'
      flipdot:
        $ref: '#/definitions/Flipdot'
      uuid:
        type: string
      settings:
        type: array
        items:
          $ref: '#/definitions/ApplicationInstanceSettingValue'
    xml:
      name: ApplicationInstance
  ApplicationInstanceSettingValue:
    type: object
    properties:
      id:
        type: integer
        format: int64
      application:
        $ref: '#/definitions/ApplicationInstance'
      applicationSetting:
        $ref: '#/definitions/ApplicationSetting'
      value:
        type: string
    xml:
      name: ApplicationInstanceSettingValue
  ApplicationSetting:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      description:
        type: string
      type:
        type: string
      defaultValue:
        type: string
      nullable:
        type: boolean
      enumerationItems:
        type: array
        items:
          $ref: '#/definitions/ApplicationSettingEnumerationItem'
      application:
        $ref: '#/definitions/Application'
    xml:
      name: ApplicationSetting
  ApplicationSettingEnumerationItem:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      value:
        type: string
    xml:
      name: ApplicationSettingEnumerationItem
  Flipdot:
    type: object
    properties:
      certificateSerial:
        type: string
      mqttChannel:
        type: string
      boardWidth:
        type: integer
      boardHeight:
        type: integer
      productionDate:
        type: string
        format: date-time
      hardwareRevision:
        type: string
      softwareVersion:
        type: string
      lastOnline:
        type: string
        format: date-time
      user:
        $ref: '#/definitions/User'
      applicationQueueItems:
        type: array
        items:
          $ref: '#/definitions/Application'
    xml:
      name: Application
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
externalDocs:
  description: Find out more about Nerdmanufaktur
  url: 'http:/nerdmanufaktur.berlin'
